version: '3.3'
services:
  mysql:
    # image: percona/percona-xtradb-cluster:latest
    image: mariadb:10.4
    # image: mysql:5.7
    # image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '127.0.0.1:3306:3306'
